server:
   port: 8070
   
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/college_local_db
      username: root
      password: root1234
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
      database-platform: org.hibernate.dialect.MySQLDialect
   